files:
- generatedChecksum: AB67D8A7D0606ADFF3E9184E6CB5B5F9
  logicalPath: config/pic32mz_ef_sk
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: AB67D8A7D0606ADFF3E9184E6CB5B5F9
- generatedChecksum: B7D9A2CB1ABC9EFC8D3EDB702CE5D4D6
  logicalPath: config/pic32mz_ef_sk
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: B7D9A2CB1ABC9EFC8D3EDB702CE5D4D6
- generatedChecksum: 4B6A778CF4449A8EC938F5D4D0917E56
  logicalPath: config/pic32mz_ef_sk
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4B6A778CF4449A8EC938F5D4D0917E56
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: B3431F6B1DCE372981EADBE16ACD913F
  logicalPath: config/pic32mz_ef_sk/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: B3431F6B1DCE372981EADBE16ACD913F
- generatedChecksum: B78784342D92F137A0446EBC260A199D
  logicalPath: config/pic32mz_ef_sk/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: B78784342D92F137A0446EBC260A199D
- generatedChecksum: 72EB8C2D6BBF51AC51BBA36862782445
  logicalPath: config/pic32mz_ef_sk/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 72EB8C2D6BBF51AC51BBA36862782445
- generatedChecksum: FCE1CC017013237DECE67A9273B1C714
  logicalPath: config/pic32mz_ef_sk/peripheral/ocmp
  name: plib_ocmp1.c
  physicalPath: peripheral/ocmp
  security: NON_SECURE
  type: SOURCE
  userChecksum: FCE1CC017013237DECE67A9273B1C714
- generatedChecksum: 6CBC84EA48AD8B13D49C502FA2115512
  logicalPath: config/pic32mz_ef_sk/peripheral/ocmp
  name: plib_ocmp2.c
  physicalPath: peripheral/ocmp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6CBC84EA48AD8B13D49C502FA2115512
- generatedChecksum: 456DFE4F24D0805414203884AC4035FE
  logicalPath: config/pic32mz_ef_sk/peripheral/ocmp
  name: plib_ocmp3.c
  physicalPath: peripheral/ocmp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 456DFE4F24D0805414203884AC4035FE
- generatedChecksum: 339BFD9FBB041A737F3908C28F11E88E
  logicalPath: config/pic32mz_ef_sk/peripheral/tmr
  name: plib_tmr2.c
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: SOURCE
  userChecksum: 339BFD9FBB041A737F3908C28F11E88E
- generatedChecksum: 71352EF41F6688AD8408E42970B50B66
  logicalPath: config/pic32mz_ef_sk/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 71352EF41F6688AD8408E42970B50B66
- generatedChecksum: 6345E78AE73D553AE22CFD19861CDD1E
  logicalPath: config/pic32mz_ef_sk
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 6345E78AE73D553AE22CFD19861CDD1E
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mz_ef_sk
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mz_ef_sk
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mz_ef_sk/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 3C465EE2268CD765C11300F75C6560CC
  logicalPath: config/pic32mz_ef_sk/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 3C465EE2268CD765C11300F75C6560CC
- generatedChecksum: FFF8E458FD7BB6E5CED45D1549F80253
  logicalPath: config/pic32mz_ef_sk/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: FFF8E458FD7BB6E5CED45D1549F80253
- generatedChecksum: 76AA999BA6C34DEAF6C37E3E0695C45E
  logicalPath: config/pic32mz_ef_sk/peripheral/ocmp
  name: plib_ocmp1.h
  physicalPath: peripheral/ocmp
  security: NON_SECURE
  type: HEADER
  userChecksum: 76AA999BA6C34DEAF6C37E3E0695C45E
- generatedChecksum: 13EE9B5E82F59CC57E429D234B2B6FB3
  logicalPath: config/pic32mz_ef_sk/peripheral/ocmp
  name: plib_ocmp2.h
  physicalPath: peripheral/ocmp
  security: NON_SECURE
  type: HEADER
  userChecksum: 13EE9B5E82F59CC57E429D234B2B6FB3
- generatedChecksum: 92F5C35DF062E420C1899CB3343BE8FA
  logicalPath: config/pic32mz_ef_sk/peripheral/ocmp
  name: plib_ocmp3.h
  physicalPath: peripheral/ocmp
  security: NON_SECURE
  type: HEADER
  userChecksum: 92F5C35DF062E420C1899CB3343BE8FA
- generatedChecksum: C7376B9C0FE98B35880E7395A16846B2
  logicalPath: config/pic32mz_ef_sk/peripheral/ocmp
  name: plib_ocmp_common.h
  physicalPath: peripheral/ocmp
  security: NON_SECURE
  type: HEADER
  userChecksum: C7376B9C0FE98B35880E7395A16846B2
- generatedChecksum: 9DF2058BBA7397756E0CED63F294C4C3
  logicalPath: config/pic32mz_ef_sk/peripheral/tmr
  name: plib_tmr2.h
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: 9DF2058BBA7397756E0CED63F294C4C3
- generatedChecksum: D948F2CE092CAB556EF299D3CCD83A55
  logicalPath: config/pic32mz_ef_sk/peripheral/tmr
  name: plib_tmr_common.h
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: D948F2CE092CAB556EF299D3CCD83A55
- generatedChecksum: CAC44960D20AEC03CF4B325A1CD2877C
  logicalPath: config/pic32mz_ef_sk
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: CAC44960D20AEC03CF4B325A1CD2877C
- generatedChecksum: C734E3299D476FDDB140E61BA3B5C31B
  logicalPath: config/pic32mz_ef_sk
  name: p32MZ2048EFH144.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: C734E3299D476FDDB140E61BA3B5C31B
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_ef_sk;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_ef_sk;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
