files:
- generatedChecksum: AB67D8A7D0606ADFF3E9184E6CB5B5F9
  logicalPath: config/pic32mz_ef_sk
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: AB67D8A7D0606ADFF3E9184E6CB5B5F9
- generatedChecksum: 19B9DB1B9A8144A8905E4400FF077491
  logicalPath: config/pic32mz_ef_sk
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 19B9DB1B9A8144A8905E4400FF077491
- generatedChecksum: 1BABDBDB07D0A03603A9B5823F63D847
  logicalPath: config/pic32mz_ef_sk
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1BABDBDB07D0A03603A9B5823F63D847
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 3421F47233DF5F61559FA850F5128C14
  logicalPath: config/pic32mz_ef_sk/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3421F47233DF5F61559FA850F5128C14
- generatedChecksum: C5C62F08FA9B10C30EED7301952387C8
  logicalPath: config/pic32mz_ef_sk/peripheral/dmac
  name: plib_dmac.c
  physicalPath: peripheral/dmac
  security: NON_SECURE
  type: SOURCE
  userChecksum: C5C62F08FA9B10C30EED7301952387C8
- generatedChecksum: 38837B2978F5B89589EE8CA0265E899A
  logicalPath: config/pic32mz_ef_sk/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 38837B2978F5B89589EE8CA0265E899A
- generatedChecksum: 381AC7E68E1E041C9421561B58BC8510
  logicalPath: config/pic32mz_ef_sk/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 381AC7E68E1E041C9421561B58BC8510
- generatedChecksum: BCDC387E1774D6F72579EBB950B8AAF7
  logicalPath: config/pic32mz_ef_sk/peripheral/spi/spi_master
  name: plib_spi1_master.c
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: SOURCE
  userChecksum: BCDC387E1774D6F72579EBB950B8AAF7
- generatedChecksum: 71352EF41F6688AD8408E42970B50B66
  logicalPath: config/pic32mz_ef_sk/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 71352EF41F6688AD8408E42970B50B66
- generatedChecksum: B43C9AE9C12D4D7FB2F7A302679C38FC
  logicalPath: config/pic32mz_ef_sk
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: B43C9AE9C12D4D7FB2F7A302679C38FC
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mz_ef_sk
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mz_ef_sk
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mz_ef_sk/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: AC36F429D7162D7D1A68B9955ED194A3
  logicalPath: config/pic32mz_ef_sk/peripheral/dmac
  name: plib_dmac.h
  physicalPath: peripheral/dmac
  security: NON_SECURE
  type: HEADER
  userChecksum: AC36F429D7162D7D1A68B9955ED194A3
- generatedChecksum: 3C465EE2268CD765C11300F75C6560CC
  logicalPath: config/pic32mz_ef_sk/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 3C465EE2268CD765C11300F75C6560CC
- generatedChecksum: 0098C66CD393C436AD4360EF7FD98A1D
  logicalPath: config/pic32mz_ef_sk/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 0098C66CD393C436AD4360EF7FD98A1D
- generatedChecksum: A9C21E81CB403E638EEB811A7780088B
  logicalPath: config/pic32mz_ef_sk/peripheral/spi/spi_master
  name: plib_spi1_master.h
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: A9C21E81CB403E638EEB811A7780088B
- generatedChecksum: CFA758C8B7258190473EF7C60C4BA4E9
  logicalPath: config/pic32mz_ef_sk/peripheral/spi/spi_master
  name: plib_spi_master_common.h
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: CFA758C8B7258190473EF7C60C4BA4E9
- generatedChecksum: CAC44960D20AEC03CF4B325A1CD2877C
  logicalPath: config/pic32mz_ef_sk
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: CAC44960D20AEC03CF4B325A1CD2877C
- generatedChecksum: C734E3299D476FDDB140E61BA3B5C31B
  logicalPath: config/pic32mz_ef_sk
  name: p32MZ2048EFH144.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: C734E3299D476FDDB140E61BA3B5C31B
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_ef_sk;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_ef_sk;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
